### ISSUE TITLE
Kamon-netty not being resolved for scala 2.11

### ISSUE THREAD

**Issue by cool-hazcker** [kamon-io/kamon-netty#3]
Hi there.
Im currently trying to add kamon-netty to our application, but it fails to be resolved. Proof pic:
![image](https://user-images.githubusercontent.com/3353419/29940105-d7ddfa82-8e96-11e7-864a-c3751dd01488.png)
![image](https://user-images.githubusercontent.com/3353419/29940119-e44efb0e-8e96-11e7-9367-adc66d8679bc.png)

We're using scala 2.11 and kamon-core v.0.6.7

**Comment by dpsoft** [comment]
Hey @cool-hazcker sorry, the documentation is not updated, you need use this version: `1.0.0-RC1-2d0f0ab696b2949ced5ac8c286f47375e3503016` for `scala 2.12.x but, is only for `Kamon` 1.0  `here the bintray repo: https://bintray.com/kamon-io/snapshots/kamon-netty/1.0.0-RC1-2d0f0ab696b2949ced5ac8c286f47375e3503016

**Comment by cool-hazcker** [comment]
Thats sad news( it requires quite an effort to migrate our current codebase to scala 2.12

**Comment by dpsoft** [comment]
@cool-hazcker I've just published in our bintray repository the version `1.0.0-RC1-b3f184afd8b0c3afc889a4ad8a56db7b780e5422` for scala `2.11` and `scala 2.12` take in account that this module is experimental and if only for the new upcoming `Kamon 1.0.0-RC1`
